### ISSUE TITLE
Worker startup call flawed in README.md

### ISSUE THREAD

**Issue by maximk** [cloudozer/BWT#3]
worker_bwt_app_app:dev() call returns undef

Probably, the right sequence to start the worker is

```
application:start(bwt).
application:start(worker_bwt_app).
```

**Comment by yatagan** [comment]
looks like I have not committed the dev function, my bad.
you are right, and also you may start lager:
lager:start()

**Comment by yatagan** [comment]
restored fun worker_bwt_app_app:dev/0 in last commits
