### ISSUE TITLE
Bug found when fastq file contains a little amount of sequences

### ISSUE THREAD

**Issue by tsybulkin** [cloudozer/BWT#4]
gen server terminates at start:

1> 08:33:01.081 [error] gen_server master terminated with reason: no case clause matching wrong_format in master:handle_call/3 line 77
08:33:01.081 [error] CRASH REPORT Process master with 2 neighbours exited with reason: no case clause matching wrong_format in master:handle_call/3 line 77 in gen_server:terminate/6 line 737

**Comment by yatagan** [comment]
Looks like your fastq file has a wrong format:

http://en.wikipedia.org/wiki/FASTQ_format

**Comment by yatagan** [comment]
Fixed in 4701ef7
